name: testing github actions

on:
  push:
    branches: [main]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repo
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: unittest
        run: go test -v

  build:
    runs-on: ubuntu-latest
    needs: audit
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/dummy:latest
            ghcr.io/anhdvu/dummy:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/dummy:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/dummy:buildcache,mode=max
